# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}


      - name: Build
        run: go build -v ./...

        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

        # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}
          echo "$aws-access-key-id"
          echo ,
          echo test, and deploy your project.
