name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run a multi-line script
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          docker build -t ${{ secrets.SuperSecret }} -f Dockerfile-app .
