name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run a multi-line script
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: ${{ secrets.SuperSecret }}