name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run a multi-line script
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world when it's Monday"
        if: ${{ secrets.TEST_ENV != 'boo' }}
        run: echo "Hello BOO"
#        if: ${{ secrets.TEST_ENV != 'boo' }}
#        run: echo "Hello BOO"
