name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world when it's Monday"
        env: 
          TEST_ENV: ${{ secrets.TEST_ENV }}
        run: |
          echo "---"
          a=${{ secrets.TEST_ENV }}
          $a
