name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world when it's Monday"
#        if: ${{ secrets.TEST_ENV == 'Mon' }}
        run: |
          a=123
          $a
