name: deploy-to-staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
        a=123
        $a